version: "3"
services:
  api:
    image: lbl-service
    build:
      context: .
    environment:
      - PORT=4711
      - MONGO_URL=mongo
    ports:
      - 4711:4711

  mongo:
    image: mongo
    ports:
      - 27017:27017